/*
 * Paged
 *
 * Handles CRUD operations for events
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"log"

	"github.com/tuuturu/paged/pkg/core/router"

	"github.com/tuuturu/paged/pkg/core"
)

func main() {
	log.Printf("Server started")

	cfg := core.LoadConfig()

	err := cfg.Validate()
	if err != nil {
		log.Fatal(err)
	}

	r := router.New(cfg)

	log.Fatal(r.Run(fmt.Sprintf(":%s", cfg.Port)))
}
