/*
 * Paged
 *
 * Handles CRUD operations for events
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"net/http"

	"github.com/tuuturu/paged/pkg/core/models"

	"github.com/tuuturu/paged/pkg/core"

	"github.com/google/uuid"

	"github.com/gin-gonic/gin"
)

// AddEvent -
func AddEvent(storage core.StorageClient) gin.HandlerFunc {
	return func(c *gin.Context) {
		event := models.Event{}

		err := c.Bind(&event)
		if err != nil {
			c.AbortWithStatus(http.StatusBadRequest)

			return
		}

		event.Id = uuid.New().String()

		err = storage.AddEvent(&event)
		if err != nil {
			c.AbortWithStatus(http.StatusInternalServerError)

			return
		}

		c.JSON(http.StatusCreated, event)
	}
}

// GetEvents -
func GetEvents(storage core.StorageClient) gin.HandlerFunc {
	return func(c *gin.Context) {
		events, err := storage.GetEvents()
		if err != nil {
			c.AbortWithStatus(http.StatusInternalServerError)

			return
		}

		c.JSON(http.StatusOK, events)
	}
}
