/*
 * Paged
 *
 * Handles CRUD operations for events
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteEvent - 
func DeleteEvent(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetEvent - 
func GetEvent(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateEvent - 
func UpdateEvent(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
