/*
 * Paged
 *
 * Handles CRUD operations for events
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Event struct {

	Id string `json:"id,omitempty"`

	TimestampStart string `json:"timestampStart,omitempty"`

	TimestampEnd string `json:"timestampEnd,omitempty"`

	Title string `json:"title,omitempty"`

	Description string `json:"description,omitempty"`

	ImageURL string `json:"imageURL,omitempty"`

	ReadMoreURL string `json:"readMoreURL,omitempty"`
}
